#!/usr/bin/env python3


##########
# Import #
##########

import os
import sys
import argparse


####################
# Globale variable #
####################


###########
# Program #
###########

def valid_key(key):

    try:
        file = open(key, 'rt')
        if file.readable():
            file_content = file.read()
            key = file_content
    except:
        pass

    if len(key) < 64:
        print("Please for -g arg give a hexadecimal key of at least 64 characters")
        exit(1)

    if not set(key).issubset(set('abcdefABCDEF0123456789')):
        print("Please for -g arg give a hexadecimal key | charset : A-F and 0-9")
        exit(1)

    return key


def parse_args():

    parser = argparse.ArgumentParser(description='ft_otp is a password generator')

    parser.add_argument('-g', help='Hexadecimal key of at least 64 characters')
    parser.add_argument('-k', help='Generates a new temporary password based on the key given as argument')

    return parser.parse_args()


def main():

    args = parse_args()

    key = valid_key(args.g)

    print(key)


if __name__ == "__main__":
    main()
